package com.mycompany.leaguetad;
// Generated 01-may-2018 19:11:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Calendario generated by hbm2java
 */
public class Calendario  implements java.io.Serializable {


     private Integer id;
     private Liga liga;
     private Date anyo;
     private Set jornadas = new HashSet(0);

    public Calendario() {
    }

    public Calendario(Liga liga, Date anyo, Set jornadas) {
       this.liga = liga;
       this.anyo = anyo;
       this.jornadas = jornadas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public Date getAnyo() {
        return this.anyo;
    }
    
    public void setAnyo(Date anyo) {
        this.anyo = anyo;
    }
    public Set getJornadas() {
        return this.jornadas;
    }
    
    public void setJornadas(Set jornadas) {
        this.jornadas = jornadas;
    }




}


