package com.mycompany.leaguetad;
// Generated 01-may-2018 19:11:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private Integer id;
     private Liga liga;
     private String nombre;
     private Integer puntos;
     private Set jugadors = new HashSet(0);
     private Set tecnicos = new HashSet(0);
     private Set partidosForLocalId = new HashSet(0);
     private Set partidosForVisitanteId = new HashSet(0);

    public Equipo() {
    }

    public Equipo(Liga liga, String nombre, Integer puntos, Set jugadors, Set tecnicos, Set partidosForLocalId, Set partidosForVisitanteId) {
       this.liga = liga;
       this.nombre = nombre;
       this.puntos = puntos;
       this.jugadors = jugadors;
       this.tecnicos = tecnicos;
       this.partidosForLocalId = partidosForLocalId;
       this.partidosForVisitanteId = partidosForVisitanteId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Liga getLiga() {
        return this.liga;
    }
    
    public void setLiga(Liga liga) {
        this.liga = liga;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    public Set getJugadors() {
        return this.jugadors;
    }
    
    public void setJugadors(Set jugadors) {
        this.jugadors = jugadors;
    }
    public Set getTecnicos() {
        return this.tecnicos;
    }
    
    public void setTecnicos(Set tecnicos) {
        this.tecnicos = tecnicos;
    }
    public Set getPartidosForLocalId() {
        return this.partidosForLocalId;
    }
    
    public void setPartidosForLocalId(Set partidosForLocalId) {
        this.partidosForLocalId = partidosForLocalId;
    }
    public Set getPartidosForVisitanteId() {
        return this.partidosForVisitanteId;
    }
    
    public void setPartidosForVisitanteId(Set partidosForVisitanteId) {
        this.partidosForVisitanteId = partidosForVisitanteId;
    }




}


