package com.mycompany.leaguetad;
// Generated 01-may-2018 19:11:12 by Hibernate Tools 4.3.1



/**
 * Estadistica generated by hbm2java
 */
public class Estadistica  implements java.io.Serializable {


     private Integer id;
     private Partido partido;
     private Integer golesLocal;
     private Integer golesVisitante;
     private Integer pasesLocal;
     private Integer pasesVisitante;
     private Integer faltasLocal;
     private Integer faltasVisitante;
     private Integer tirosLocal;
     private Integer tirosVisitante;

    public Estadistica() {
    }

    public Estadistica(Partido partido, Integer golesLocal, Integer golesVisitante, Integer pasesLocal, Integer pasesVisitante, Integer faltasLocal, Integer faltasVisitante, Integer tirosLocal, Integer tirosVisitante) {
       this.partido = partido;
       this.golesLocal = golesLocal;
       this.golesVisitante = golesVisitante;
       this.pasesLocal = pasesLocal;
       this.pasesVisitante = pasesVisitante;
       this.faltasLocal = faltasLocal;
       this.faltasVisitante = faltasVisitante;
       this.tirosLocal = tirosLocal;
       this.tirosVisitante = tirosVisitante;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Partido getPartido() {
        return this.partido;
    }
    
    public void setPartido(Partido partido) {
        this.partido = partido;
    }
    public Integer getGolesLocal() {
        return this.golesLocal;
    }
    
    public void setGolesLocal(Integer golesLocal) {
        this.golesLocal = golesLocal;
    }
    public Integer getGolesVisitante() {
        return this.golesVisitante;
    }
    
    public void setGolesVisitante(Integer golesVisitante) {
        this.golesVisitante = golesVisitante;
    }
    public Integer getPasesLocal() {
        return this.pasesLocal;
    }
    
    public void setPasesLocal(Integer pasesLocal) {
        this.pasesLocal = pasesLocal;
    }
    public Integer getPasesVisitante() {
        return this.pasesVisitante;
    }
    
    public void setPasesVisitante(Integer pasesVisitante) {
        this.pasesVisitante = pasesVisitante;
    }
    public Integer getFaltasLocal() {
        return this.faltasLocal;
    }
    
    public void setFaltasLocal(Integer faltasLocal) {
        this.faltasLocal = faltasLocal;
    }
    public Integer getFaltasVisitante() {
        return this.faltasVisitante;
    }
    
    public void setFaltasVisitante(Integer faltasVisitante) {
        this.faltasVisitante = faltasVisitante;
    }
    public Integer getTirosLocal() {
        return this.tirosLocal;
    }
    
    public void setTirosLocal(Integer tirosLocal) {
        this.tirosLocal = tirosLocal;
    }
    public Integer getTirosVisitante() {
        return this.tirosVisitante;
    }
    
    public void setTirosVisitante(Integer tirosVisitante) {
        this.tirosVisitante = tirosVisitante;
    }




}


