package com.mycompany.leaguetad;
// Generated 01-may-2018 19:11:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jornada generated by hbm2java
 */
public class Jornada  implements java.io.Serializable {


     private Integer id;
     private Calendario calendario;
     private Integer numero;
     private Date fecha;
     private Set partidos = new HashSet(0);

    public Jornada() {
    }

    public Jornada(Calendario calendario, Integer numero, Date fecha, Set partidos) {
       this.calendario = calendario;
       this.numero = numero;
       this.fecha = fecha;
       this.partidos = partidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Calendario getCalendario() {
        return this.calendario;
    }
    
    public void setCalendario(Calendario calendario) {
        this.calendario = calendario;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set partidos) {
        this.partidos = partidos;
    }




}


