package com.mycompany.leaguetad;
// Generated 01-may-2018 19:11:12 by Hibernate Tools 4.3.1



/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private Integer id;
     private Equipo equipo;
     private String nombre;
     private String nacionalidad;
     private String posicion;
     private Integer edad;
     private Integer goles;
     private Integer pases;
     private Integer faltas;
     private Integer expulsiones;
     private Integer paradas;
     private Integer tiros;

    public Jugador() {
    }

    public Jugador(Equipo equipo, String nombre, String nacionalidad, String posicion, Integer edad, Integer goles, Integer pases, Integer faltas, Integer expulsiones, Integer paradas, Integer tiros) {
       this.equipo = equipo;
       this.nombre = nombre;
       this.nacionalidad = nacionalidad;
       this.posicion = posicion;
       this.edad = edad;
       this.goles = goles;
       this.pases = pases;
       this.faltas = faltas;
       this.expulsiones = expulsiones;
       this.paradas = paradas;
       this.tiros = tiros;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(String posicion) {
        this.posicion = posicion;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Integer getGoles() {
        return this.goles;
    }
    
    public void setGoles(Integer goles) {
        this.goles = goles;
    }
    public Integer getPases() {
        return this.pases;
    }
    
    public void setPases(Integer pases) {
        this.pases = pases;
    }
    public Integer getFaltas() {
        return this.faltas;
    }
    
    public void setFaltas(Integer faltas) {
        this.faltas = faltas;
    }
    public Integer getExpulsiones() {
        return this.expulsiones;
    }
    
    public void setExpulsiones(Integer expulsiones) {
        this.expulsiones = expulsiones;
    }
    public Integer getParadas() {
        return this.paradas;
    }
    
    public void setParadas(Integer paradas) {
        this.paradas = paradas;
    }
    public Integer getTiros() {
        return this.tiros;
    }
    
    public void setTiros(Integer tiros) {
        this.tiros = tiros;
    }




}


