package com.mycompany.leaguetad;
// Generated 01-may-2018 19:11:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Liga generated by hbm2java
 */
public class Liga  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String pais;
     private Set calendarios = new HashSet(0);
     private Set equipos = new HashSet(0);

    public Liga() {
    }

    public Liga(String nombre, String pais, Set calendarios, Set equipos) {
       this.nombre = nombre;
       this.pais = pais;
       this.calendarios = calendarios;
       this.equipos = equipos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getCalendarios() {
        return this.calendarios;
    }
    
    public void setCalendarios(Set calendarios) {
        this.calendarios = calendarios;
    }
    public Set getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set equipos) {
        this.equipos = equipos;
    }




}


