package com.mycompany.leaguetad;
// Generated 01-may-2018 19:11:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private Integer id;
     private Equipo equipoByLocalId;
     private Equipo equipoByVisitanteId;
     private Jornada jornada;
     private Set estadisticas = new HashSet(0);

    public Partido() {
    }

    public Partido(Equipo equipoByLocalId, Equipo equipoByVisitanteId, Jornada jornada, Set estadisticas) {
       this.equipoByLocalId = equipoByLocalId;
       this.equipoByVisitanteId = equipoByVisitanteId;
       this.jornada = jornada;
       this.estadisticas = estadisticas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Equipo getEquipoByLocalId() {
        return this.equipoByLocalId;
    }
    
    public void setEquipoByLocalId(Equipo equipoByLocalId) {
        this.equipoByLocalId = equipoByLocalId;
    }
    public Equipo getEquipoByVisitanteId() {
        return this.equipoByVisitanteId;
    }
    
    public void setEquipoByVisitanteId(Equipo equipoByVisitanteId) {
        this.equipoByVisitanteId = equipoByVisitanteId;
    }
    public Jornada getJornada() {
        return this.jornada;
    }
    
    public void setJornada(Jornada jornada) {
        this.jornada = jornada;
    }
    public Set getEstadisticas() {
        return this.estadisticas;
    }
    
    public void setEstadisticas(Set estadisticas) {
        this.estadisticas = estadisticas;
    }




}


