package com.mycompany.leaguetad;
// Generated 01-may-2018 19:11:12 by Hibernate Tools 4.3.1



/**
 * Tecnico generated by hbm2java
 */
public class Tecnico  implements java.io.Serializable {


     private Integer id;
     private Equipo equipo;
     private String nombre;
     private String puesto;

    public Tecnico() {
    }

    public Tecnico(Equipo equipo, String nombre, String puesto) {
       this.equipo = equipo;
       this.nombre = nombre;
       this.puesto = puesto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }




}


